// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profiles.Infrastructure.Persistence;

#nullable disable

namespace Profiles.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240606011406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CityModel", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("cty_city_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("cty_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cty_name");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("prv_province_id");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Name", "ProvinceId")
                        .IsUnique();

                    b.ToTable("city");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("67aa556d-18ac-41de-987d-dce1a0c1a22c"),
                            Disabled = false,
                            Name = "Leticia",
                            ProvinceId = new Guid("6142179e-b85a-445b-b192-13c55e0fde7a")
                        },
                        new
                        {
                            CityId = new Guid("a350888c-acdd-43ee-8c17-071ee14c09ed"),
                            Disabled = false,
                            Name = "Medellín",
                            ProvinceId = new Guid("b667da90-18aa-4332-bfcc-98180817039f")
                        },
                        new
                        {
                            CityId = new Guid("0406e2e7-b2a6-4fcd-a077-9f871effa12f"),
                            Disabled = false,
                            Name = "Apartadó",
                            ProvinceId = new Guid("b667da90-18aa-4332-bfcc-98180817039f")
                        },
                        new
                        {
                            CityId = new Guid("500f6857-0063-44d2-9154-fac9b796c949"),
                            Disabled = false,
                            Name = "Turbo",
                            ProvinceId = new Guid("b667da90-18aa-4332-bfcc-98180817039f")
                        },
                        new
                        {
                            CityId = new Guid("c35d297e-e211-4424-a19a-f56fd923f297"),
                            Disabled = false,
                            Name = "Arauca",
                            ProvinceId = new Guid("2624291f-182d-4183-84f4-5eaf4fdc2db6")
                        },
                        new
                        {
                            CityId = new Guid("829c3233-0fcf-43c7-b425-416a952506ef"),
                            Disabled = false,
                            Name = "Saravena",
                            ProvinceId = new Guid("2624291f-182d-4183-84f4-5eaf4fdc2db6")
                        },
                        new
                        {
                            CityId = new Guid("fd67d2e7-5640-43e6-8036-f102032ca31a"),
                            Disabled = false,
                            Name = "Fortul",
                            ProvinceId = new Guid("2624291f-182d-4183-84f4-5eaf4fdc2db6")
                        },
                        new
                        {
                            CityId = new Guid("66d33583-0cfb-4f74-a10e-01e1fd22a9a4"),
                            Disabled = false,
                            Name = "Barranquilla",
                            ProvinceId = new Guid("62761b57-94ac-49f8-ac2e-a68b54f0985a")
                        },
                        new
                        {
                            CityId = new Guid("77c30b63-6e79-4c28-9d51-ff9436182f9e"),
                            Disabled = false,
                            Name = "Soledad",
                            ProvinceId = new Guid("62761b57-94ac-49f8-ac2e-a68b54f0985a")
                        },
                        new
                        {
                            CityId = new Guid("31b3ec71-b68f-4e9e-8c82-43f5cdc438d6"),
                            Disabled = false,
                            Name = "Puerto Colombia",
                            ProvinceId = new Guid("62761b57-94ac-49f8-ac2e-a68b54f0985a")
                        },
                        new
                        {
                            CityId = new Guid("b277e4ea-9a38-4f83-a41d-4421a1eb3bd8"),
                            Disabled = false,
                            Name = "Cartagena de Indias",
                            ProvinceId = new Guid("5ce551fe-655e-49a7-95ad-e113f65b0e6f")
                        },
                        new
                        {
                            CityId = new Guid("780ac94b-dd4f-415a-ac91-76405c7ad412"),
                            Disabled = false,
                            Name = "Magangué",
                            ProvinceId = new Guid("5ce551fe-655e-49a7-95ad-e113f65b0e6f")
                        },
                        new
                        {
                            CityId = new Guid("482c7897-f05c-4193-8a71-fff6cba454ca"),
                            Disabled = false,
                            Name = "Cartagena del Chairá",
                            ProvinceId = new Guid("5ce551fe-655e-49a7-95ad-e113f65b0e6f")
                        },
                        new
                        {
                            CityId = new Guid("667e5dee-e41a-4dee-866b-4fa072bb5679"),
                            Disabled = false,
                            Name = "Tunja",
                            ProvinceId = new Guid("bd57297e-b985-4190-ae3a-2a04ba486325")
                        },
                        new
                        {
                            CityId = new Guid("503d6aa5-033e-4128-81b2-c03e499cb6a0"),
                            Disabled = false,
                            Name = "Sogamoso",
                            ProvinceId = new Guid("bd57297e-b985-4190-ae3a-2a04ba486325")
                        },
                        new
                        {
                            CityId = new Guid("0a300b00-6aca-4316-ad69-68393706d26e"),
                            Disabled = false,
                            Name = "Duitama",
                            ProvinceId = new Guid("bd57297e-b985-4190-ae3a-2a04ba486325")
                        },
                        new
                        {
                            CityId = new Guid("60be401f-89fd-456a-91be-9c54289fa5f8"),
                            Disabled = false,
                            Name = "Manizales",
                            ProvinceId = new Guid("60991494-70c3-4a03-9ef1-1d1d97429c42")
                        },
                        new
                        {
                            CityId = new Guid("cdba1c83-635e-45ee-9994-0869f3e5f1f0"),
                            Disabled = false,
                            Name = "Pereira",
                            ProvinceId = new Guid("60991494-70c3-4a03-9ef1-1d1d97429c42")
                        },
                        new
                        {
                            CityId = new Guid("e4d6e2cc-9a65-49ed-8c99-229d96ae688e"),
                            Disabled = false,
                            Name = "Chinchiná",
                            ProvinceId = new Guid("60991494-70c3-4a03-9ef1-1d1d97429c42")
                        },
                        new
                        {
                            CityId = new Guid("bfb855e0-a9f6-4574-88ca-b63fd02ca980"),
                            Disabled = false,
                            Name = "Florencia",
                            ProvinceId = new Guid("02baec1c-81e0-4f0e-90a1-9107d469777c")
                        },
                        new
                        {
                            CityId = new Guid("e65a8883-fc11-407c-b9ea-9bcafa16bc08"),
                            Disabled = false,
                            Name = "Cartagena del Chairá",
                            ProvinceId = new Guid("02baec1c-81e0-4f0e-90a1-9107d469777c")
                        },
                        new
                        {
                            CityId = new Guid("0075ed9a-5e38-4227-a075-a84ce7bc4f7b"),
                            Disabled = false,
                            Name = "Morelia",
                            ProvinceId = new Guid("02baec1c-81e0-4f0e-90a1-9107d469777c")
                        },
                        new
                        {
                            CityId = new Guid("c4bd3f2c-b8cc-46f0-b423-eed06cdc2d6a"),
                            Disabled = false,
                            Name = "Yopal",
                            ProvinceId = new Guid("cc406ecc-7147-4f55-8096-46016755d3d6")
                        },
                        new
                        {
                            CityId = new Guid("a47eb0d7-d871-45ba-b81a-9e42d3235fe5"),
                            Disabled = false,
                            Name = "Aguazul",
                            ProvinceId = new Guid("cc406ecc-7147-4f55-8096-46016755d3d6")
                        },
                        new
                        {
                            CityId = new Guid("96eec8cb-30d7-48ee-a3b2-01cc740ecb6d"),
                            Disabled = false,
                            Name = "Tauramena",
                            ProvinceId = new Guid("cc406ecc-7147-4f55-8096-46016755d3d6")
                        },
                        new
                        {
                            CityId = new Guid("f001c309-806a-487e-adf5-5225854d4733"),
                            Disabled = false,
                            Name = "Popayán",
                            ProvinceId = new Guid("0adc5d72-3b8f-40d6-a55b-039bf971ab21")
                        },
                        new
                        {
                            CityId = new Guid("e6a880f7-4841-4532-9ff9-781f93f7af95"),
                            Disabled = false,
                            Name = "Silvia",
                            ProvinceId = new Guid("0adc5d72-3b8f-40d6-a55b-039bf971ab21")
                        },
                        new
                        {
                            CityId = new Guid("83251d2c-048b-4940-9778-e466e698292c"),
                            Disabled = false,
                            Name = "Santander de Quilichao",
                            ProvinceId = new Guid("0adc5d72-3b8f-40d6-a55b-039bf971ab21")
                        },
                        new
                        {
                            CityId = new Guid("944ce583-9648-432a-9c77-6b6a46f14542"),
                            Disabled = false,
                            Name = "Valledupar",
                            ProvinceId = new Guid("dcf423b2-e93d-41fc-bc0a-8669ee52230d")
                        },
                        new
                        {
                            CityId = new Guid("7ccd0563-a966-4f60-8718-91a66404f8b2"),
                            Disabled = false,
                            Name = "Aguachica",
                            ProvinceId = new Guid("dcf423b2-e93d-41fc-bc0a-8669ee52230d")
                        },
                        new
                        {
                            CityId = new Guid("879b2843-3078-41ef-a59a-2e1c0aba27b5"),
                            Disabled = false,
                            Name = "La Paz",
                            ProvinceId = new Guid("dcf423b2-e93d-41fc-bc0a-8669ee52230d")
                        },
                        new
                        {
                            CityId = new Guid("0741b7e4-a898-4f39-8a8b-165d6c4ddfa0"),
                            Disabled = false,
                            Name = "Quibdó",
                            ProvinceId = new Guid("885f08a2-3c01-47bd-8362-11e75024e207")
                        },
                        new
                        {
                            CityId = new Guid("08245541-7669-4ae8-959f-aa9445565b26"),
                            Disabled = false,
                            Name = "Istmina",
                            ProvinceId = new Guid("885f08a2-3c01-47bd-8362-11e75024e207")
                        },
                        new
                        {
                            CityId = new Guid("b8306d49-ce74-41cb-b8ba-0bd057f91c01"),
                            Disabled = false,
                            Name = "Novita",
                            ProvinceId = new Guid("885f08a2-3c01-47bd-8362-11e75024e207")
                        },
                        new
                        {
                            CityId = new Guid("8748d8b8-29de-432d-8b6c-d874291bd3a7"),
                            Disabled = false,
                            Name = "Montería",
                            ProvinceId = new Guid("20d9774c-9e67-434a-8db9-21e14b7aef47")
                        },
                        new
                        {
                            CityId = new Guid("dbbaeb56-13ca-4731-8a28-6eee80aa29e7"),
                            Disabled = false,
                            Name = "Cereté",
                            ProvinceId = new Guid("20d9774c-9e67-434a-8db9-21e14b7aef47")
                        },
                        new
                        {
                            CityId = new Guid("9199f7ca-d3c1-4aad-b139-3d02aa53dc28"),
                            Disabled = false,
                            Name = "Lorica",
                            ProvinceId = new Guid("20d9774c-9e67-434a-8db9-21e14b7aef47")
                        },
                        new
                        {
                            CityId = new Guid("f73086a8-a50e-4fb5-8670-fa6b901ea95e"),
                            Disabled = false,
                            Name = "Bogotá",
                            ProvinceId = new Guid("ef552fa0-def3-4c9f-87a9-5b914387b7d5")
                        },
                        new
                        {
                            CityId = new Guid("953c3d65-a5eb-4744-8d1c-972d9d37f2a9"),
                            Disabled = false,
                            Name = "Soacha",
                            ProvinceId = new Guid("ef552fa0-def3-4c9f-87a9-5b914387b7d5")
                        },
                        new
                        {
                            CityId = new Guid("92041d07-8908-4eb3-808e-b71570873ec8"),
                            Disabled = false,
                            Name = "Zipaquirá",
                            ProvinceId = new Guid("ef552fa0-def3-4c9f-87a9-5b914387b7d5")
                        },
                        new
                        {
                            CityId = new Guid("e4eef7a9-de9d-454b-92c4-136d4bad12fd"),
                            Disabled = false,
                            Name = "Inírida",
                            ProvinceId = new Guid("75ad794e-0be4-4cf9-8bd3-162426433a1f")
                        },
                        new
                        {
                            CityId = new Guid("7728cb00-1225-46e6-9b2c-9f197ed2aff5"),
                            Disabled = false,
                            Name = "Puerto Inírida",
                            ProvinceId = new Guid("75ad794e-0be4-4cf9-8bd3-162426433a1f")
                        },
                        new
                        {
                            CityId = new Guid("df3f27a1-0f48-479d-8fb7-f15818462b6f"),
                            Disabled = false,
                            Name = "Memarí",
                            ProvinceId = new Guid("75ad794e-0be4-4cf9-8bd3-162426433a1f")
                        },
                        new
                        {
                            CityId = new Guid("303e5bad-6d33-4ed5-9e7b-cecf537dcbab"),
                            Disabled = false,
                            Name = "San José del Guaviare",
                            ProvinceId = new Guid("7816b4fa-f3da-4672-94c3-b827c1e04070")
                        },
                        new
                        {
                            CityId = new Guid("8d3235e1-b654-4b45-bec8-fdf7526e878f"),
                            Disabled = false,
                            Name = "Calamar",
                            ProvinceId = new Guid("7816b4fa-f3da-4672-94c3-b827c1e04070")
                        },
                        new
                        {
                            CityId = new Guid("a355bf04-da4d-4818-b3a4-4bb1eff67242"),
                            Disabled = false,
                            Name = "El Retén",
                            ProvinceId = new Guid("7816b4fa-f3da-4672-94c3-b827c1e04070")
                        },
                        new
                        {
                            CityId = new Guid("0c8cd540-e02b-4137-b688-e019dea27870"),
                            Disabled = false,
                            Name = "Neiva",
                            ProvinceId = new Guid("f1df1f3f-5616-444d-9bff-9ff1b94a0c56")
                        },
                        new
                        {
                            CityId = new Guid("efcc3454-6316-44c8-9d07-943fd25216cf"),
                            Disabled = false,
                            Name = "Garzón",
                            ProvinceId = new Guid("f1df1f3f-5616-444d-9bff-9ff1b94a0c56")
                        },
                        new
                        {
                            CityId = new Guid("1dd1625b-f0ad-4cba-b02e-d18cc24dbd9e"),
                            Disabled = false,
                            Name = "Pitalito",
                            ProvinceId = new Guid("f1df1f3f-5616-444d-9bff-9ff1b94a0c56")
                        },
                        new
                        {
                            CityId = new Guid("4d10b530-ee6d-4a2c-a0a5-2feed79f9274"),
                            Disabled = false,
                            Name = "Riohacha",
                            ProvinceId = new Guid("2b0a16b1-5a5c-4520-a885-837980b73ec9")
                        },
                        new
                        {
                            CityId = new Guid("1899aec0-2b3d-43f0-bf3e-a6ed03160c5b"),
                            Disabled = false,
                            Name = "Maicao",
                            ProvinceId = new Guid("2b0a16b1-5a5c-4520-a885-837980b73ec9")
                        },
                        new
                        {
                            CityId = new Guid("80d263bf-1b56-44c5-aba0-9d2f79cadb1a"),
                            Disabled = false,
                            Name = "Uribia",
                            ProvinceId = new Guid("2b0a16b1-5a5c-4520-a885-837980b73ec9")
                        },
                        new
                        {
                            CityId = new Guid("423cd6b4-38ca-455f-9c1b-de8a1c1117d6"),
                            Disabled = false,
                            Name = "Santa Marta",
                            ProvinceId = new Guid("16f922a3-4c19-432c-a822-415a40f6c13a")
                        },
                        new
                        {
                            CityId = new Guid("5c5577f4-1c69-4d7f-9ad6-28733e074d6f"),
                            Disabled = false,
                            Name = "Aracataca",
                            ProvinceId = new Guid("16f922a3-4c19-432c-a822-415a40f6c13a")
                        },
                        new
                        {
                            CityId = new Guid("267ae103-7fb4-40e0-be1c-2e9e148a7fb5"),
                            Disabled = false,
                            Name = "Ciénaga",
                            ProvinceId = new Guid("16f922a3-4c19-432c-a822-415a40f6c13a")
                        },
                        new
                        {
                            CityId = new Guid("bdf16bce-b945-442d-b59d-c0ea00fab6a8"),
                            Disabled = false,
                            Name = "Villavicencio",
                            ProvinceId = new Guid("55bb69fb-01a2-41b0-aa1d-6bb3e3828e46")
                        },
                        new
                        {
                            CityId = new Guid("48542efb-77ba-4a28-9928-b3bd8963a97e"),
                            Disabled = false,
                            Name = "Acacias",
                            ProvinceId = new Guid("55bb69fb-01a2-41b0-aa1d-6bb3e3828e46")
                        },
                        new
                        {
                            CityId = new Guid("54b94edb-7730-4313-a7b5-b11fc582c1de"),
                            Disabled = false,
                            Name = "Granada",
                            ProvinceId = new Guid("55bb69fb-01a2-41b0-aa1d-6bb3e3828e46")
                        },
                        new
                        {
                            CityId = new Guid("0cf3ee89-11af-4f00-a081-e875bcd88d97"),
                            Disabled = false,
                            Name = "San Juan de Pasto",
                            ProvinceId = new Guid("6ce4ee7c-57ee-456d-a90b-1ff3c9ffc62a")
                        },
                        new
                        {
                            CityId = new Guid("9cc85076-8a5b-49bf-a7eb-ec931debad85"),
                            Disabled = false,
                            Name = "Tumaco",
                            ProvinceId = new Guid("6ce4ee7c-57ee-456d-a90b-1ff3c9ffc62a")
                        },
                        new
                        {
                            CityId = new Guid("21bb6731-0377-404d-9898-928657e6074f"),
                            Disabled = false,
                            Name = "Ipiales",
                            ProvinceId = new Guid("6ce4ee7c-57ee-456d-a90b-1ff3c9ffc62a")
                        },
                        new
                        {
                            CityId = new Guid("f94d18ea-d353-453b-821d-cfde3786fa30"),
                            Disabled = false,
                            Name = "Cúcuta",
                            ProvinceId = new Guid("02fdcc0c-4ccb-4385-8443-b423f044555c")
                        },
                        new
                        {
                            CityId = new Guid("a6bfd88b-4e06-4741-82a6-bb0e5f183211"),
                            Disabled = false,
                            Name = "Ocaña",
                            ProvinceId = new Guid("02fdcc0c-4ccb-4385-8443-b423f044555c")
                        },
                        new
                        {
                            CityId = new Guid("a2bc46f4-617d-4aa8-a5f2-cfadfa2000c1"),
                            Disabled = false,
                            Name = "Pamplona",
                            ProvinceId = new Guid("02fdcc0c-4ccb-4385-8443-b423f044555c")
                        },
                        new
                        {
                            CityId = new Guid("acb83f6c-64d0-452e-b601-a92222aa16e4"),
                            Disabled = false,
                            Name = "Mocoa",
                            ProvinceId = new Guid("7edc4b28-27d9-404e-9d41-eb112e72b2e3")
                        },
                        new
                        {
                            CityId = new Guid("7da8269d-7d34-439b-b920-9831512ff309"),
                            Disabled = false,
                            Name = "Puerto Asís",
                            ProvinceId = new Guid("7edc4b28-27d9-404e-9d41-eb112e72b2e3")
                        },
                        new
                        {
                            CityId = new Guid("abb06001-ad72-40fd-8e10-3a42ab7cae7e"),
                            Disabled = false,
                            Name = "Orito",
                            ProvinceId = new Guid("7edc4b28-27d9-404e-9d41-eb112e72b2e3")
                        },
                        new
                        {
                            CityId = new Guid("3b31f60f-dfb6-4e82-bbf0-776f6ce9a771"),
                            Disabled = false,
                            Name = "Armenia",
                            ProvinceId = new Guid("5dd698b1-29ba-4728-a324-f64deda85fc9")
                        },
                        new
                        {
                            CityId = new Guid("57a8cdae-9003-4c9d-83b8-55aa16516d92"),
                            Disabled = false,
                            Name = "Calarcá",
                            ProvinceId = new Guid("5dd698b1-29ba-4728-a324-f64deda85fc9")
                        },
                        new
                        {
                            CityId = new Guid("613e4e18-bdcc-4595-929d-1600fb3b66a2"),
                            Disabled = false,
                            Name = "La Tebaida",
                            ProvinceId = new Guid("5dd698b1-29ba-4728-a324-f64deda85fc9")
                        },
                        new
                        {
                            CityId = new Guid("75546d87-8873-4c68-9741-c999726ccd19"),
                            Disabled = false,
                            Name = "Pereira",
                            ProvinceId = new Guid("3bc8bea0-0772-4466-a1e0-8bf22bf3f2c2")
                        },
                        new
                        {
                            CityId = new Guid("958b75c2-f2fb-4e79-9477-1a50454063bd"),
                            Disabled = false,
                            Name = "Dosquebradas",
                            ProvinceId = new Guid("3bc8bea0-0772-4466-a1e0-8bf22bf3f2c2")
                        },
                        new
                        {
                            CityId = new Guid("53cfa130-3a16-45a7-b7f1-5521675b0d5c"),
                            Disabled = false,
                            Name = "Santa Rosa de Cabal",
                            ProvinceId = new Guid("3bc8bea0-0772-4466-a1e0-8bf22bf3f2c2")
                        },
                        new
                        {
                            CityId = new Guid("cd14e393-9acd-4057-8f56-0ba0568e6a3f"),
                            Disabled = false,
                            Name = "San Andrés",
                            ProvinceId = new Guid("99cd5f3c-b591-4a1a-8574-c5b82ea0d337")
                        },
                        new
                        {
                            CityId = new Guid("b2dd01ae-f2eb-4cbc-98a1-02a2b594d1b7"),
                            Disabled = false,
                            Name = "Providencia",
                            ProvinceId = new Guid("99cd5f3c-b591-4a1a-8574-c5b82ea0d337")
                        },
                        new
                        {
                            CityId = new Guid("d4f30256-322d-4516-9635-52ce0a7e08cd"),
                            Disabled = false,
                            Name = "Santa Catalina",
                            ProvinceId = new Guid("99cd5f3c-b591-4a1a-8574-c5b82ea0d337")
                        },
                        new
                        {
                            CityId = new Guid("f05bb9d7-2f09-4c70-86d1-63590652a70e"),
                            Disabled = false,
                            Name = "Bucaramanga",
                            ProvinceId = new Guid("3accd102-139e-4b54-a266-dba40c5a1d77")
                        },
                        new
                        {
                            CityId = new Guid("08a4b71e-5001-457e-ada2-56d81f267c27"),
                            Disabled = false,
                            Name = "Barrancabermeja",
                            ProvinceId = new Guid("3accd102-139e-4b54-a266-dba40c5a1d77")
                        },
                        new
                        {
                            CityId = new Guid("e7d7c30a-73ea-4065-bd20-d73e0ad5da7e"),
                            Disabled = false,
                            Name = "Piedecuesta",
                            ProvinceId = new Guid("3accd102-139e-4b54-a266-dba40c5a1d77")
                        },
                        new
                        {
                            CityId = new Guid("e7926c43-fe03-4e61-bdf6-5ddf441fee97"),
                            Disabled = false,
                            Name = "Sincelejo",
                            ProvinceId = new Guid("c6da6aa6-0d49-449d-8487-b940f4ce1648")
                        },
                        new
                        {
                            CityId = new Guid("4ef78282-aa9d-4ddf-b246-05e633c0e9a5"),
                            Disabled = false,
                            Name = "Corozal",
                            ProvinceId = new Guid("c6da6aa6-0d49-449d-8487-b940f4ce1648")
                        },
                        new
                        {
                            CityId = new Guid("18ad6719-f234-4de3-8c09-160af8916d06"),
                            Disabled = false,
                            Name = "Montería",
                            ProvinceId = new Guid("c6da6aa6-0d49-449d-8487-b940f4ce1648")
                        },
                        new
                        {
                            CityId = new Guid("2e5e2e50-60b0-4eca-812e-36c0a8d93bf7"),
                            Disabled = false,
                            Name = "Ibagué",
                            ProvinceId = new Guid("7faa43bf-7415-4097-8f56-aa900c2fe772")
                        },
                        new
                        {
                            CityId = new Guid("5d1b63e3-77ef-45f1-bebb-019f8108327f"),
                            Disabled = false,
                            Name = "Honda",
                            ProvinceId = new Guid("7faa43bf-7415-4097-8f56-aa900c2fe772")
                        },
                        new
                        {
                            CityId = new Guid("0e1131bb-4f37-4761-b39c-9570327e6ace"),
                            Disabled = false,
                            Name = "Armero Guayabal",
                            ProvinceId = new Guid("7faa43bf-7415-4097-8f56-aa900c2fe772")
                        },
                        new
                        {
                            CityId = new Guid("74dffbca-1a3a-4aae-949e-e977c8aa57f1"),
                            Disabled = false,
                            Name = "Cali",
                            ProvinceId = new Guid("714d1455-c57c-4686-9b34-18b663d93d38")
                        },
                        new
                        {
                            CityId = new Guid("7121ebfd-7dc1-45e6-9945-14f89516d71f"),
                            Disabled = false,
                            Name = "Palmira",
                            ProvinceId = new Guid("714d1455-c57c-4686-9b34-18b663d93d38")
                        },
                        new
                        {
                            CityId = new Guid("cb596d7c-8c4d-4068-b5c8-bcbe68d04a61"),
                            Disabled = false,
                            Name = "Buenaventura",
                            ProvinceId = new Guid("714d1455-c57c-4686-9b34-18b663d93d38")
                        },
                        new
                        {
                            CityId = new Guid("c1206606-0f4d-4045-8af0-cd21b59ef6a7"),
                            Disabled = false,
                            Name = "Mitú",
                            ProvinceId = new Guid("f17a7d74-8a10-49b3-92d9-14f21cc6dd24")
                        },
                        new
                        {
                            CityId = new Guid("0b363116-0d32-4b71-b9af-89ed3b36a4fe"),
                            Disabled = false,
                            Name = "Yavaraté",
                            ProvinceId = new Guid("f17a7d74-8a10-49b3-92d9-14f21cc6dd24")
                        },
                        new
                        {
                            CityId = new Guid("e78d3674-2661-40f9-a631-91309fc5e170"),
                            Disabled = false,
                            Name = "Santa Rosalía",
                            ProvinceId = new Guid("f17a7d74-8a10-49b3-92d9-14f21cc6dd24")
                        },
                        new
                        {
                            CityId = new Guid("bb385d16-893a-4310-9108-73a85d2ca4a5"),
                            Disabled = false,
                            Name = "Puerto Carreño",
                            ProvinceId = new Guid("6d184776-b4b5-43e8-972a-0281f7d3cb15")
                        },
                        new
                        {
                            CityId = new Guid("8ac5b047-765e-4a06-9208-35483a83e9cd"),
                            Disabled = false,
                            Name = "La Primavera",
                            ProvinceId = new Guid("6d184776-b4b5-43e8-972a-0281f7d3cb15")
                        },
                        new
                        {
                            CityId = new Guid("779398b6-edc4-4a26-b65b-8f5b1db0eb00"),
                            Disabled = false,
                            Name = "Santa Helena",
                            ProvinceId = new Guid("6d184776-b4b5-43e8-972a-0281f7d3cb15")
                        },
                        new
                        {
                            CityId = new Guid("ea3a972c-981c-4a28-a7a1-788565c57603"),
                            Disabled = false,
                            Name = "Cuenca",
                            ProvinceId = new Guid("9e19aff9-071a-4173-9f03-188d08d8a269")
                        },
                        new
                        {
                            CityId = new Guid("d97f35c9-27b7-400f-b9db-879bd9103598"),
                            Disabled = false,
                            Name = "Girón",
                            ProvinceId = new Guid("9e19aff9-071a-4173-9f03-188d08d8a269")
                        },
                        new
                        {
                            CityId = new Guid("48d86fc7-ab2c-4f16-92e7-305b8af4041c"),
                            Disabled = false,
                            Name = "Guaranda",
                            ProvinceId = new Guid("47c6c58c-31aa-40c4-946c-bb206bbf893b")
                        },
                        new
                        {
                            CityId = new Guid("0afe0ce5-5cb2-4568-ae6a-a19dc1600980"),
                            Disabled = false,
                            Name = "San Miguel de Bolívar",
                            ProvinceId = new Guid("47c6c58c-31aa-40c4-946c-bb206bbf893b")
                        },
                        new
                        {
                            CityId = new Guid("a998d35a-81c9-4619-a86b-f11d992503fa"),
                            Disabled = false,
                            Name = "Azogues",
                            ProvinceId = new Guid("e1683fb9-da94-4b64-9402-541b2a65b5bd")
                        },
                        new
                        {
                            CityId = new Guid("706bb490-6b0c-462f-b907-446ba54e20ed"),
                            Disabled = false,
                            Name = "El Tambo",
                            ProvinceId = new Guid("e1683fb9-da94-4b64-9402-541b2a65b5bd")
                        },
                        new
                        {
                            CityId = new Guid("0c65fd0c-ad28-4661-9f70-0b7006ae9e60"),
                            Disabled = false,
                            Name = "Tulcán",
                            ProvinceId = new Guid("0613864e-c378-4e2e-813f-35da9a9745b2")
                        },
                        new
                        {
                            CityId = new Guid("9f69cc64-e6cd-4e3b-becc-e852c5668031"),
                            Disabled = false,
                            Name = "El Guabo",
                            ProvinceId = new Guid("0613864e-c378-4e2e-813f-35da9a9745b2")
                        },
                        new
                        {
                            CityId = new Guid("35fe0b03-0d6c-416d-ac12-c7c37e34f829"),
                            Disabled = false,
                            Name = "Riobamba",
                            ProvinceId = new Guid("12408d66-333b-4495-8a5c-b82f577d6483")
                        },
                        new
                        {
                            CityId = new Guid("74418bdd-b62f-4028-927e-10740233bab0"),
                            Disabled = false,
                            Name = "Alausí",
                            ProvinceId = new Guid("12408d66-333b-4495-8a5c-b82f577d6483")
                        },
                        new
                        {
                            CityId = new Guid("85b6ad39-d5f6-4932-ad39-c8b5932b55d4"),
                            Disabled = false,
                            Name = "Latacunga",
                            ProvinceId = new Guid("a437622c-a366-470c-a8c1-6e57ca71689a")
                        },
                        new
                        {
                            CityId = new Guid("a8795a4c-c953-4bea-aa36-9307064f3219"),
                            Disabled = false,
                            Name = "Salcedo",
                            ProvinceId = new Guid("a437622c-a366-470c-a8c1-6e57ca71689a")
                        },
                        new
                        {
                            CityId = new Guid("c6215ccf-f6bb-4651-af2e-e540fc151fb5"),
                            Disabled = false,
                            Name = "Machala",
                            ProvinceId = new Guid("471dc235-a393-46d6-9dac-e68fded03e44")
                        },
                        new
                        {
                            CityId = new Guid("648397b4-3b71-4f1a-81fc-40b24a7cd335"),
                            Disabled = false,
                            Name = "Santa Rosa",
                            ProvinceId = new Guid("471dc235-a393-46d6-9dac-e68fded03e44")
                        },
                        new
                        {
                            CityId = new Guid("10a18e71-d50b-4cc9-aea9-4ee1d05bae21"),
                            Disabled = false,
                            Name = "Esmeraldas",
                            ProvinceId = new Guid("ccddf62c-d27e-4d6a-97a8-2b24bcf763cb")
                        },
                        new
                        {
                            CityId = new Guid("0f99d66c-0918-4ed0-b079-7c59c53ef816"),
                            Disabled = false,
                            Name = "Atacames",
                            ProvinceId = new Guid("ccddf62c-d27e-4d6a-97a8-2b24bcf763cb")
                        },
                        new
                        {
                            CityId = new Guid("9d293ca8-0e41-4d25-bbf8-82c232f23da4"),
                            Disabled = false,
                            Name = "Puerto Baquerizo Moreno",
                            ProvinceId = new Guid("0142d0da-56e2-4a6a-8d19-c1447fd88e45")
                        },
                        new
                        {
                            CityId = new Guid("4bd497a1-7d0e-4d66-8377-b337e52cd246"),
                            Disabled = false,
                            Name = "San Cristóbal",
                            ProvinceId = new Guid("0142d0da-56e2-4a6a-8d19-c1447fd88e45")
                        },
                        new
                        {
                            CityId = new Guid("b22f7f37-1200-4367-8b8d-9ee0d1a7e084"),
                            Disabled = false,
                            Name = "Guayaquil",
                            ProvinceId = new Guid("5a03edca-c978-46ff-94c1-d90fab048198")
                        },
                        new
                        {
                            CityId = new Guid("9ebb8f39-6278-4aea-95e6-7f654635a376"),
                            Disabled = false,
                            Name = "Durán",
                            ProvinceId = new Guid("5a03edca-c978-46ff-94c1-d90fab048198")
                        },
                        new
                        {
                            CityId = new Guid("96a8ae8d-9731-4d92-a877-ac3bcbe3e26e"),
                            Disabled = false,
                            Name = "Ibarra",
                            ProvinceId = new Guid("3d155301-298f-4294-b9ae-f99f2750ade9")
                        },
                        new
                        {
                            CityId = new Guid("bc07dddd-ffd6-4664-aa20-e012fecfcffb"),
                            Disabled = false,
                            Name = "Otavalo",
                            ProvinceId = new Guid("3d155301-298f-4294-b9ae-f99f2750ade9")
                        },
                        new
                        {
                            CityId = new Guid("ca14a316-11fd-47ff-8eec-9354029a9acb"),
                            Disabled = false,
                            Name = "Loja",
                            ProvinceId = new Guid("8a92bf7a-8302-4e80-871d-fbd4340c9b81")
                        },
                        new
                        {
                            CityId = new Guid("c675d340-117a-4a81-a07f-1afb9adc1f1c"),
                            Disabled = false,
                            Name = "Saraguro",
                            ProvinceId = new Guid("8a92bf7a-8302-4e80-871d-fbd4340c9b81")
                        },
                        new
                        {
                            CityId = new Guid("ca595c0c-edc5-410b-ad23-55367af0028b"),
                            Disabled = false,
                            Name = "Portoviejo",
                            ProvinceId = new Guid("29b67093-6129-4ee5-8255-5ba86b1bf59d")
                        },
                        new
                        {
                            CityId = new Guid("69470eec-4891-4712-b2d8-cb571f370e73"),
                            Disabled = false,
                            Name = "Manta",
                            ProvinceId = new Guid("29b67093-6129-4ee5-8255-5ba86b1bf59d")
                        },
                        new
                        {
                            CityId = new Guid("832cb8c5-452f-4940-b7d4-634e3703527e"),
                            Disabled = false,
                            Name = "Chone",
                            ProvinceId = new Guid("29b67093-6129-4ee5-8255-5ba86b1bf59d")
                        },
                        new
                        {
                            CityId = new Guid("6bde3a64-6c2e-4c1f-83d5-d98fbd15b734"),
                            Disabled = false,
                            Name = "Macas",
                            ProvinceId = new Guid("22ee9fff-0a8c-4600-bb17-7eeeff6a2a99")
                        },
                        new
                        {
                            CityId = new Guid("97d06d95-683e-4637-baa1-b5699f555cfb"),
                            Disabled = false,
                            Name = "Gualaquiza",
                            ProvinceId = new Guid("22ee9fff-0a8c-4600-bb17-7eeeff6a2a99")
                        },
                        new
                        {
                            CityId = new Guid("c2544eb3-7b16-467f-8451-a4e746c7ac12"),
                            Disabled = false,
                            Name = "Tena",
                            ProvinceId = new Guid("674ddb31-9a94-45a1-893b-d88d9c6837d6")
                        },
                        new
                        {
                            CityId = new Guid("6ab81e51-cd9f-4a41-aff8-26c0f99e8626"),
                            Disabled = false,
                            Name = "Archidona",
                            ProvinceId = new Guid("674ddb31-9a94-45a1-893b-d88d9c6837d6")
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CountryModel", b =>
                {
                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ctr_country_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("ctr_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctr_name");

                    b.HasKey("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("country");

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Colombia"
                        },
                        new
                        {
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Ecuador"
                        },
                        new
                        {
                            CountryId = new Guid("5a63237b-d0e6-4603-89d1-656f7f0d8a3b"),
                            Disabled = false,
                            Name = "Venezuela"
                        },
                        new
                        {
                            CountryId = new Guid("925d036e-8958-44be-9b38-05a0eb0f3bd0"),
                            Disabled = false,
                            Name = "Panamá"
                        },
                        new
                        {
                            CountryId = new Guid("63570461-5f95-40ba-b205-88ebbb14529c"),
                            Disabled = false,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            CountryId = new Guid("68e44283-9fc2-4b82-a6e8-80877c164b0f"),
                            Disabled = false,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            CountryId = new Guid("4b1fc2c0-ddc8-4552-918e-137e09894c88"),
                            Disabled = false,
                            Name = "Honduras"
                        },
                        new
                        {
                            CountryId = new Guid("f9fcf0d6-0364-4782-9c06-7300cdaef975"),
                            Disabled = false,
                            Name = "Guatemala"
                        },
                        new
                        {
                            CountryId = new Guid("f96128d0-a6d2-4638-81a7-0b1053dde626"),
                            Disabled = false,
                            Name = "El Salvador"
                        },
                        new
                        {
                            CountryId = new Guid("fe84b3d9-2b31-4186-96e8-f40776825324"),
                            Disabled = false,
                            Name = "Belize"
                        },
                        new
                        {
                            CountryId = new Guid("4ff85abd-6bb3-4122-b5c8-e06848957c8e"),
                            Disabled = false,
                            Name = "México"
                        },
                        new
                        {
                            CountryId = new Guid("df9218c6-6071-4583-a482-6c2f69c76926"),
                            Disabled = false,
                            Name = "Perú"
                        },
                        new
                        {
                            CountryId = new Guid("81dacc73-8484-4519-bf6d-a9c0b5503901"),
                            Disabled = false,
                            Name = "Chile"
                        },
                        new
                        {
                            CountryId = new Guid("ce60c6f2-c39e-4d77-a91c-8700d327467d"),
                            Disabled = false,
                            Name = "Argentina"
                        },
                        new
                        {
                            CountryId = new Guid("7997a384-5a0b-4968-be42-c8466cc286b0"),
                            Disabled = false,
                            Name = "Brasil"
                        },
                        new
                        {
                            CountryId = new Guid("1a002345-c49e-4057-aff9-052fb936db36"),
                            Disabled = false,
                            Name = "Paraguay"
                        },
                        new
                        {
                            CountryId = new Guid("a442ffb9-7dee-4c16-b2c0-1de534afec93"),
                            Disabled = false,
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryId = new Guid("21a134df-0b33-4098-be50-bef01f0916fa"),
                            Disabled = false,
                            Name = "Bolivia"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.LevelModel", b =>
                {
                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_level_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rol_description");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rol_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("LevelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("level");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProfessionalModel", b =>
                {
                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("prf_professional_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("prf_disabled");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prf_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prf_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProfessionalId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("professional");

                    b.HasData(
                        new
                        {
                            ProfessionalId = new Guid("a0c61d04-be3e-46f7-b702-be78a388f238"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7812),
                            Disabled = false,
                            Email = "juanperez@gmail.com",
                            Name = "Juan Pérez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("56d59143-01ba-475c-9fd3-d153bc1d73ca"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7820),
                            Disabled = false,
                            Email = "mariagarcia@gmail.com",
                            Name = "María García"
                        },
                        new
                        {
                            ProfessionalId = new Guid("d4d82078-b9b9-4454-a526-1feff8efb456"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7845),
                            Disabled = false,
                            Email = "pedrolopez@gmail.com",
                            Name = "Pedro López"
                        },
                        new
                        {
                            ProfessionalId = new Guid("d81f48f7-eff9-4d66-96a6-127c33a71c1d"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7849),
                            Disabled = false,
                            Email = "anasanchez@gmail.com",
                            Name = "Ana Sánchez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("7ca4d0a7-3578-4648-b797-8e8520435cac"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7853),
                            Disabled = false,
                            Email = "carlosrodriguez@gmail.com",
                            Name = "Carlos Rodríguez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("23c84402-a063-4f14-ad92-ca511fbf4147"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7858),
                            Disabled = false,
                            Email = "isabelmartinez@gmail.com",
                            Name = "Isabel Martínez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("bcd93c44-a805-4c99-9fd5-4d2a3ed282c4"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7862),
                            Disabled = false,
                            Email = "diegogomez@gmail.com",
                            Name = "Diego Gómez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("a5c0c24d-0077-4955-96c2-9e8562599eef"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7866),
                            Disabled = false,
                            Email = "sandramoreno@gmail.com",
                            Name = "Sandra Moreno"
                        },
                        new
                        {
                            ProfessionalId = new Guid("e7f23c52-0ddc-47df-b8cc-65d3bf619d8e"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7869),
                            Disabled = false,
                            Email = "andresfernandez@gmail.com",
                            Name = "Andrés Fernández"
                        },
                        new
                        {
                            ProfessionalId = new Guid("85788fc7-5ebc-429c-b8b0-da32eb473fba"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7874),
                            Disabled = false,
                            Email = "lauragonzalez@gmail.com",
                            Name = "Laura González"
                        },
                        new
                        {
                            ProfessionalId = new Guid("b328688b-1c96-46c4-b743-731e90be5c54"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7878),
                            Disabled = false,
                            Email = "javiermunoz@gmail.com",
                            Name = "Javier Muñoz"
                        },
                        new
                        {
                            ProfessionalId = new Guid("66fd5605-0c9b-4328-8b63-cfb9ecf2144b"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7882),
                            Disabled = false,
                            Email = "patriciablanco@gmail.com",
                            Name = "Patricia Blanco"
                        },
                        new
                        {
                            ProfessionalId = new Guid("bdc99ecc-5987-44c0-a40e-5131381d0484"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7886),
                            Disabled = false,
                            Email = "josegutierrez@gmail.com",
                            Name = "José Gutiérrez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("b959aa21-f0f9-4da0-81f9-32857f6324d9"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7889),
                            Disabled = false,
                            Email = "aliciaruis@gmail.com",
                            Name = "Alicia Ruiz"
                        },
                        new
                        {
                            ProfessionalId = new Guid("7476282c-383a-466c-9cc6-4188ac3af9b0"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7893),
                            Disabled = false,
                            Email = "luisvazquez@gmail.com",
                            Name = "Luis Vázquez"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("prv_province_id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ctr_country_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("prv_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prv_name");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique();

                    b.ToTable("province");

                    b.HasData(
                        new
                        {
                            ProvinceId = new Guid("6142179e-b85a-445b-b192-13c55e0fde7a"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Amazonas"
                        },
                        new
                        {
                            ProvinceId = new Guid("b667da90-18aa-4332-bfcc-98180817039f"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Antioquia"
                        },
                        new
                        {
                            ProvinceId = new Guid("2624291f-182d-4183-84f4-5eaf4fdc2db6"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Arauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("62761b57-94ac-49f8-ac2e-a68b54f0985a"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Atlántico"
                        },
                        new
                        {
                            ProvinceId = new Guid("5ce551fe-655e-49a7-95ad-e113f65b0e6f"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Bolívar"
                        },
                        new
                        {
                            ProvinceId = new Guid("bd57297e-b985-4190-ae3a-2a04ba486325"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Boyacá"
                        },
                        new
                        {
                            ProvinceId = new Guid("60991494-70c3-4a03-9ef1-1d1d97429c42"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Caldas"
                        },
                        new
                        {
                            ProvinceId = new Guid("02baec1c-81e0-4f0e-90a1-9107d469777c"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Caquetá"
                        },
                        new
                        {
                            ProvinceId = new Guid("cc406ecc-7147-4f55-8096-46016755d3d6"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Casanare"
                        },
                        new
                        {
                            ProvinceId = new Guid("0adc5d72-3b8f-40d6-a55b-039bf971ab21"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Cauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("dcf423b2-e93d-41fc-bc0a-8669ee52230d"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Cesar"
                        },
                        new
                        {
                            ProvinceId = new Guid("885f08a2-3c01-47bd-8362-11e75024e207"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Chocó"
                        },
                        new
                        {
                            ProvinceId = new Guid("20d9774c-9e67-434a-8db9-21e14b7aef47"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Córdoba"
                        },
                        new
                        {
                            ProvinceId = new Guid("ef552fa0-def3-4c9f-87a9-5b914387b7d5"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Cundinamarca"
                        },
                        new
                        {
                            ProvinceId = new Guid("75ad794e-0be4-4cf9-8bd3-162426433a1f"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Guainía"
                        },
                        new
                        {
                            ProvinceId = new Guid("7816b4fa-f3da-4672-94c3-b827c1e04070"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Guaviare"
                        },
                        new
                        {
                            ProvinceId = new Guid("f1df1f3f-5616-444d-9bff-9ff1b94a0c56"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Huila"
                        },
                        new
                        {
                            ProvinceId = new Guid("2b0a16b1-5a5c-4520-a885-837980b73ec9"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "La Guajira"
                        },
                        new
                        {
                            ProvinceId = new Guid("16f922a3-4c19-432c-a822-415a40f6c13a"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Magdalena"
                        },
                        new
                        {
                            ProvinceId = new Guid("55bb69fb-01a2-41b0-aa1d-6bb3e3828e46"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Meta"
                        },
                        new
                        {
                            ProvinceId = new Guid("6ce4ee7c-57ee-456d-a90b-1ff3c9ffc62a"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Nariño"
                        },
                        new
                        {
                            ProvinceId = new Guid("02fdcc0c-4ccb-4385-8443-b423f044555c"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Norte de Santander"
                        },
                        new
                        {
                            ProvinceId = new Guid("7edc4b28-27d9-404e-9d41-eb112e72b2e3"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Putumayo"
                        },
                        new
                        {
                            ProvinceId = new Guid("5dd698b1-29ba-4728-a324-f64deda85fc9"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Quindío"
                        },
                        new
                        {
                            ProvinceId = new Guid("3bc8bea0-0772-4466-a1e0-8bf22bf3f2c2"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Risaralda"
                        },
                        new
                        {
                            ProvinceId = new Guid("99cd5f3c-b591-4a1a-8574-c5b82ea0d337"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "San Andrés y Providencia"
                        },
                        new
                        {
                            ProvinceId = new Guid("3accd102-139e-4b54-a266-dba40c5a1d77"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Santander"
                        },
                        new
                        {
                            ProvinceId = new Guid("c6da6aa6-0d49-449d-8487-b940f4ce1648"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Sucre"
                        },
                        new
                        {
                            ProvinceId = new Guid("7faa43bf-7415-4097-8f56-aa900c2fe772"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Tolima"
                        },
                        new
                        {
                            ProvinceId = new Guid("714d1455-c57c-4686-9b34-18b663d93d38"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Valle del Cauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("f17a7d74-8a10-49b3-92d9-14f21cc6dd24"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Vaupés"
                        },
                        new
                        {
                            ProvinceId = new Guid("6d184776-b4b5-43e8-972a-0281f7d3cb15"),
                            CountryId = new Guid("951a7fd8-230c-4d8a-a68a-b20aec5f4e95"),
                            Disabled = false,
                            Name = "Vichada"
                        },
                        new
                        {
                            ProvinceId = new Guid("9e19aff9-071a-4173-9f03-188d08d8a269"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Azuay"
                        },
                        new
                        {
                            ProvinceId = new Guid("47c6c58c-31aa-40c4-946c-bb206bbf893b"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Bolívar"
                        },
                        new
                        {
                            ProvinceId = new Guid("e1683fb9-da94-4b64-9402-541b2a65b5bd"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Cañar"
                        },
                        new
                        {
                            ProvinceId = new Guid("0613864e-c378-4e2e-813f-35da9a9745b2"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Carchi"
                        },
                        new
                        {
                            ProvinceId = new Guid("12408d66-333b-4495-8a5c-b82f577d6483"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Chimborazo"
                        },
                        new
                        {
                            ProvinceId = new Guid("a437622c-a366-470c-a8c1-6e57ca71689a"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Cotopaxi"
                        },
                        new
                        {
                            ProvinceId = new Guid("471dc235-a393-46d6-9dac-e68fded03e44"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "El Oro"
                        },
                        new
                        {
                            ProvinceId = new Guid("ccddf62c-d27e-4d6a-97a8-2b24bcf763cb"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Esmeraldas"
                        },
                        new
                        {
                            ProvinceId = new Guid("0142d0da-56e2-4a6a-8d19-c1447fd88e45"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Galápagos"
                        },
                        new
                        {
                            ProvinceId = new Guid("5a03edca-c978-46ff-94c1-d90fab048198"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Guayas"
                        },
                        new
                        {
                            ProvinceId = new Guid("3d155301-298f-4294-b9ae-f99f2750ade9"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Imbabura"
                        },
                        new
                        {
                            ProvinceId = new Guid("8a92bf7a-8302-4e80-871d-fbd4340c9b81"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Loja"
                        },
                        new
                        {
                            ProvinceId = new Guid("29b67093-6129-4ee5-8255-5ba86b1bf59d"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Manabí"
                        },
                        new
                        {
                            ProvinceId = new Guid("22ee9fff-0a8c-4600-bb17-7eeeff6a2a99"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Morona Santiago"
                        },
                        new
                        {
                            ProvinceId = new Guid("674ddb31-9a94-45a1-893b-d88d9c6837d6"),
                            CountryId = new Guid("7c6ca238-8b60-4a1e-a1b2-a2d381069cf4"),
                            Disabled = false,
                            Name = "Napo"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.RoleModel", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_role_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rol_description");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rol_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("role");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("b5000d60-90c7-433f-a9bb-a91d4ac7c733"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7656),
                            Disabled = false,
                            Name = "Developer"
                        },
                        new
                        {
                            RoleId = new Guid("d253068f-843a-4ad7-b5a6-035e83c065bc"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7662),
                            Disabled = false,
                            Name = "Designer"
                        },
                        new
                        {
                            RoleId = new Guid("72f25a1b-25c0-402f-a607-3c96f3ed90b3"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7666),
                            Disabled = false,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = new Guid("08e844c8-d7ba-46bd-b8e5-f4593ad4c14e"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7670),
                            Disabled = false,
                            Name = "QA"
                        },
                        new
                        {
                            RoleId = new Guid("57a39ac1-e148-4ce7-afa1-0ba5a3b2593b"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7674),
                            Disabled = false,
                            Name = "DevOps"
                        },
                        new
                        {
                            RoleId = new Guid("45142aa4-0a8e-4f15-af46-03c5a1f643a1"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7679),
                            Disabled = false,
                            Name = "Data Scientist"
                        },
                        new
                        {
                            RoleId = new Guid("b4793973-453a-41cf-bb1c-630f67deabfb"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7682),
                            Disabled = false,
                            Name = "UX/UI Designer"
                        },
                        new
                        {
                            RoleId = new Guid("784fe2b3-29e4-4330-8397-739962ad70d3"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7686),
                            Disabled = false,
                            Name = "Product Owner"
                        },
                        new
                        {
                            RoleId = new Guid("17f63ad7-4c5a-4f2a-9210-f7b198f6c838"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7690),
                            Disabled = false,
                            Name = "Scrum Master"
                        },
                        new
                        {
                            RoleId = new Guid("d665c05b-62a1-40da-a598-68367f437da3"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7694),
                            Disabled = false,
                            Name = "Architect"
                        },
                        new
                        {
                            RoleId = new Guid("f6c8e0ad-918e-4f90-95d1-8ac5542b0426"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7698),
                            Disabled = false,
                            Name = "Lead Developer"
                        },
                        new
                        {
                            RoleId = new Guid("0f38e6c7-adf9-4a75-9a33-eba0655ab26a"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7701),
                            Disabled = false,
                            Name = "Lead Designer"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.SkillModel", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skl_skill_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("skl_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("skl_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skill");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("9fa76d5b-38b4-4ad3-8828-384506e3f7db"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7724),
                            Disabled = false,
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("5d5e77c5-81e4-47e3-8f63-1bc5c0db6461"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7730),
                            Disabled = false,
                            Name = "Java"
                        },
                        new
                        {
                            SkillId = new Guid("7be23de2-ae7d-4173-a887-4ef0001cab6e"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7734),
                            Disabled = false,
                            Name = "Python"
                        },
                        new
                        {
                            SkillId = new Guid("cd3fba82-8b2d-46e4-be20-9352172cdfb8"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7738),
                            Disabled = false,
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("aff33eea-30e8-4159-88e2-b868b7cb62ab"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7741),
                            Disabled = false,
                            Name = "TypeScript"
                        },
                        new
                        {
                            SkillId = new Guid("50e2b8f4-3e30-4574-80fb-cb8d6771ad06"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7746),
                            Disabled = false,
                            Name = "HTML"
                        },
                        new
                        {
                            SkillId = new Guid("bfa749e8-3330-453a-9060-524b3656fc81"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7749),
                            Disabled = false,
                            Name = "CSS"
                        },
                        new
                        {
                            SkillId = new Guid("5c4b817a-21cc-46b6-971f-56e544239fcd"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7753),
                            Disabled = false,
                            Name = "SQL"
                        },
                        new
                        {
                            SkillId = new Guid("c03ffed4-5c3f-493c-8432-dbb33cfba677"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7756),
                            Disabled = false,
                            Name = "NoSQL"
                        },
                        new
                        {
                            SkillId = new Guid("a618e994-345c-45eb-8f26-7bdccc78c8f3"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7760),
                            Disabled = false,
                            Name = "Angular"
                        },
                        new
                        {
                            SkillId = new Guid("8a874dc5-ee4a-4b4a-b2b0-4e28e586ecbb"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7767),
                            Disabled = false,
                            Name = "React"
                        },
                        new
                        {
                            SkillId = new Guid("0bfa4de1-3408-41b4-89e5-6d3fc48760e0"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7768),
                            Disabled = false,
                            Name = "Vue"
                        },
                        new
                        {
                            SkillId = new Guid("4d710637-5854-4575-ad1d-1977c3ffd88d"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7771),
                            Disabled = false,
                            Name = "Node.js"
                        },
                        new
                        {
                            SkillId = new Guid("fe5fc9b7-da0c-475b-bfc6-cf27c8dea48b"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7775),
                            Disabled = false,
                            Name = "Spring Boot"
                        },
                        new
                        {
                            SkillId = new Guid("a89f8793-46ab-44e2-afde-27afa29ed80a"),
                            CreatedAt = new DateTime(2024, 6, 6, 1, 14, 6, 432, DateTimeKind.Utc).AddTicks(7778),
                            Disabled = false,
                            Name = "Hibernate"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CityModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.ProvinceModel", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.CountryModel", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CountryModel", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
